### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #3.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by dpryan79** [comment]
@cpauvert This will (hopefully) fix the issue

**Comment by dpryan79** [comment]
@conda-forge-admin please rerender

**Comment by dpryan79** [comment]
Hmm, I don't think this will work, there seems to be a more fundamental issue with the staging channel.

**Comment by dpryan79** [comment]
OK, well the rerun of master seems to have done something: https://anaconda.org/cf-staging/r-plnmodels/files

**Comment by cpauvert** [comment]
> OK, well the rerun of master seems to have done something: https://anaconda.org/cf-staging/r-plnmodels/files

Yes it seems! Thanks! The previous error disappeared (at least) on the linux 64 tests!

**Comment by cpauvert** [comment]
The issue #1 is closed then I'm closing this PR. Thank you @dpryan79 :)

**Pull request closed without merging**
