### PR TITLE
Increment build number (fixes #1)

### LINKED ISSUE #1: TimeOutError: Did not manage to upload package.  Failing
Issue: Azure tests fail because of lack of upload to anaconda.

<br/>
Environment : `Azure linux_64_r_base3.6` and R4 
<br/>

The error was mentioned by the bot: https://github.com/conda-forge/r-plnmodels-feedstock/commit/a08e87d8e2f94055bd085f050e033a0673a1d3d1#commitcomment-43842366

The package was correctly [installed](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=235295&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=758) and [loaded](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=235295&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=1055) but from what I understand, the issue comes from the upload of the package to anaconda.org ([link](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=235295&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=1101)). They were 9 trys, all failed and Azure quitted on error.

I will upgrade the build number (as per the README and this [issue](https://github.com/conda-forge/spdlog-feedstock/issues/28)) to try to solve

### PR DESCRIPTION
**Pull request by cpauvert**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cpauvert** [comment]
@conda-forge-admin, please rerender

**Comment by dpryan79** [comment]
Oh, please use a fork when working on feedstocks! You may have just inadvertently pushed a package with your changes.

**Comment by dpryan79** [comment]
I've hit rerun for the master branch on azure.

**Comment by cpauvert** [comment]
> Oh, please use a fork when working on feedstocks! You may have just inadvertently pushed a package with your changes.

Oh crap, I thought I did! I'm sorry, I thought of changing branches and the PR but not the fork

**Comment by dpryan79** [comment]
Pretty sure we've all done this :)

**Comment by cpauvert** [comment]
Ok. @chrisburr on the chat said that it might have been a _behind-the-scenes_ errors. Does your rerun should bypass that?

**Comment by dpryan79** [comment]
I hope so

**Pull request closed without merging**
